### ISSUE TITLE
Set-TdIncidentTimeSpent $IncidentNumber -TimeSpent 5 -Notes 'note text'

### ISSUE THREAD

**Issue by HHTabbert** [AndrewPla/TOPdeskPS#114]
Invoke-RestMethod : No valid authentication token provided

+         $result = Invoke-RestMethod @parameter -ErrorAction Stop
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by HHTabbert** [comment]
Stupid mistake, forget it

**Comment by AndrewPla** [comment]
No worries. The same thing happens to me sometimes. Have a great rest of your week.
