### ISSUE TITLE
Add support to create persons

### ISSUE THREAD

**Issue by whatthehomepod** [AndrewPla/TOPdeskPS#26]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
Add support to create persons. I love this script however almost all the other commands are useless (for me). 
We have a script that creates user accounts based on input, however we want to create persons as well after creating an AD-account. I don't know how REST API works.

**Examples of how the solution would work**
For example: 
$firstname = Read-Host -prompt ‘Enter firstname’. 

New-TdPerson -firstname $firstname -aduser $aduser ETC, you get it.

**Describe alternatives you've considered**
A way to do it myself, however I don't know where to start.

**Additional context**
n/a

**Comment by AndrewPla** [comment]
Great idea! This is definitely something that should be a part of this module. This project is still in it's infancy so there are many other commands that still need to be created. Once I add the command I'll let you know and can show you how it works. There are a few steps required, but I'd be more than happy to break it down for you.

**Comment by whatthehomepod** [comment]
This would be awesome! Thank you. Though I’m not a developer I’m for sure we can help each other! :-) 

Verstuurd vanaf mijn iPhone

**Comment by whatthehomepod** [comment]
@AndrewPla do you have a timetable how long this can take? :)
Because this needs to be implemented on our department asap.
I can start a support ticket with TOPdesk to check if they can help me out.

**Comment by AndrewPla** [comment]
Currently being implemented in PR #27

**Comment by AndrewPla** [comment]
Currently supported in v0.0.5
