### ISSUE TITLE
The required module 'PSFramework' is not loaded.

### ISSUE THREAD

**Issue by whatthehomepod** [AndrewPla/TOPdeskPS#29]
**Prerequisites**

Put an X between the brackets on each line to confirm you have completed them:

- [x] The issue is still present in the latest version of the module.
- [x] The issue has not been previously reported.

**Describe the bug**
I cannot install modules but I can load them **normally** with Import-Module and when I place the script into C:\Users\null\Documents\WindowsPowerShell\TOPdeskPS\
I did that with NTFSSecurity and Write-Ascii however with TOPdeskPS the following error is shown: The required module 'PSFramework' is not loaded.

**To Reproduce**
n/a

**Expected behavior**
n/a

**Screenshots or Transcripts**
n/a

**System Details**

- Operating System: [Windows | Linux | MacOS]
Windows Server 2012 R2 Datacenter

- Operating System Version (Version and Build, eg Windows 10 Build 1709):
Windows Server 2012 R2 Datacenter

- PowerShell Version: [Use ```Get-Host```]
5.1.14409.1005

- Architecture for PowerShell Session: [64bit | 32bit]
64bit

- Is this system an Azure Automation Worker?: [No, Hybrid Worker, Azure Worker]
No

- Other loaded modules: [Include the output of ```Get-Module```]
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}

**Additional context**
n/a

**Comment by AndrewPla** [comment]
This is due to the fact that the TOPdeskPS module has a dependency on the
module PSFramework. You will also need to install
https://github.com/PowershellFrameworkCollective/psframework/tree/master/PSFramework

Usually this is handled behind the scenes when you run Install-Module, but
since you are bypassing that you will need to manually get them.

**Comment by whatthehomepod** [comment]
The specified module 'PSFramework' with version '0.10.27.128' was not loaded because no valid module file was found in any modul
e directory.

**Comment by AndrewPla** [comment]
Glad to hear it worked out for you.
