### ISSUE TITLE
PowerShell Core Compatibility

### ISSUE THREAD

**Issue by AndrewPla** [AndrewPla/TOPdeskPS#51]
Let's make this bad boy PS Core compatible.

**Comment by AndrewPla** [comment]
Most commands work fine. I need to work on the Commmands that send files to incidents/changes/assets.

The request is a multi part form that I manually create in Windows PowerShell (it's very ugly and I think that I will improve that command as well when I'm here.)

I need to add a new parameterto the Invoke-TdMethod command that accepts a file then sendse it as a multipart request. Seperating the logic of dealing with pscore/windows powershell will be done inside the invoke-tdmethod command.

Example of sending a multi part request in PS Core

```powershell
$Uri = 'https://api.contoso.com/v2/profile'
$Form = @{
    firstName  = 'John'
    lastName   = 'Doe'
    email      = 'john.doe@contoso.com'
    avatar     = Get-Item -Path 'c:\Pictures\jdoe.png'
    birthday   = '1980-10-15'
    hobbies    = 'Hiking','Fishing','Jogging'
}
$Result = Invoke-RestMethod -Uri $Uri -Method Post -Form $Form
```
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-6

**Comment by AndrewPla** [comment]
So I also realize that there are a few parameters on the File Upload POST request that we aren't using. We aren't using the description or the 'InvisibleForCaller' switches.

I am going to work on adding support for those additional parameters in another issue. For now I will just make uploading a file the way it is now on both PSCore and WinPS

**Comment by AndrewPla** [comment]
All commands have been updated and tested on Windows. I want to try sending some files from linux and ensure that my `-file` Parameters on my send- commands work properly

**Comment by jeffreytigch** [comment]
Seeing that there is already an issue for this, I installed this on a Mac with Powershell Core 6.1.0. After import, I got this error:

```
PS /Users/$user> Install-Module -Name TOPdeskPS

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this 
repository, change its InstallationPolicy value by running the Set-PSRepository
 cmdlet. Are you sure you want to install the modules from 'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help 
(default is "N"):y

PS /Users/$user> Import-Module TOPdeskPS
Exception calling "ReadAllText" with "1" argument(s): "Could not find file '/usr/local/share/powershell/Modules/TOPdeskPS/0.0.8\internal\scripts\preimport.ps1'."                                                                               At /usr/local/share/powershell/Modules/TOPdeskPS/0.0.8/TOPdeskPS.psm1:31 char:12+     else { $ExecutionContext.InvokeCommand.InvokeScript($false, ([scr ...     +            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~         + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException       + FullyQualifiedErrorId : FileNotFoundException                                 
 
Exception calling "ReadAllText" with "1" argument(s): "Could not find file '/usr/local/share/powershell/Modules/TOPdeskPS/0.0.8\internal\scripts\postimport.ps1'."
At /usr/local/share/powershell/Modules/TOPdeskPS/0.0.8/TOPdeskPS.psm1:31 char:12
+     else { $ExecutionContext.InvokeCommand.InvokeScript($false, ([scr ...
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : FileNotFoundException
```

**Comment by AndrewPla** [comment]
Thanks for the feedback. I just published v0.0.10 which *should* have fixed your issue. Give it an install and let me know how it goes for you. 
`Install-Module topdeskps -MinimumVersion 0.0.10`

**Comment by AndrewPla** [comment]
@jeffreytigch If you have any issues connecting let me now. I have also updated the readme to include a link to https://developers.topdesk.com/tutorial.html#show-collapse-config-topdesk which shows you how to assign api permissions to your logon and how to create an application password if you choose.

Let me know how the experience goes for you so I can update the docs to help everyone get started faster.

**Comment by jeffreytigch** [comment]
Thanks for the quick update. I am a user of Topdeskl not an admin, so I can't help you with the permissions unfortunately. 

Regarding the update, I now got another error. Will place it in the PR, it seems like the same problem.

**Comment by AndrewPla** [comment]
Module is working from my Ubuntu machine and master branch is all up to date. Version 0.0.15 of the module is good to go.
