### ISSUE TITLE
New-TdIncident Options

### ISSUE THREAD

**Issue by digitalexpl0it** [AndrewPla/TOPdeskPS#68]
When creating a new Incident is there a way to set the Operator and Operator Group?

**Comment by digitalexpl0it** [comment]
Or have an option output the ticket number after using New-TdIncident

**Comment by AndrewPla** [comment]
Thanks for raising this issue. It definitely looks like New-TdIncident could use some love. It looks like there are a few parameters I need to add a bunch of new parameters to New-TdIncident. 

https://developers.topdesk.com/documentation/index.html#api-Incident-CreateIncident

**Comment by digitalexpl0it** [comment]
We have multiple departments using TOPDesk and we filter the ticket based off Operator Group, so an option to specify the Operator Group would be a great addition.

**Comment by AndrewPla** [comment]
The latest version of TOPdeskPS on the gallery now has the updated New-TdIncident command. Let me know if you see any other issues
