### ISSUE TITLE
Incident SLA

### ISSUE THREAD

**Issue by BND-ErwinVos** [AndrewPla/TOPdeskPS#72]
**Is your feature request related to a problem? Please describe.**
We use Service Level Agreements on our incidents. I can close incidents with the module, but I cannot link an SLA.

**Describe the solution you'd like**
Be able to link an SLA

**Examples of how the solution would work**
n/a

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by AndrewPla** [comment]
If this is something that you'd like to explore further, can you grab an SLA id? To do that you will need to run 
`Get-TdIncident | Select -ExpandPropert sla `
We will need to use that Sla Id, so hold onto that.

Once we have our Sla Id we can try sending the id to an incident and see if it links it.
We can use Invoke-TdMethod to send a custom request that I haven't added to the module yet.

```powershell
Connect-TdService 
$SlaId = '1234-abcd-1234-abcd' # use the sla Id that we grabbed earlier.
$Number = 'I123-123' # Number of incident that we want to try to link an SLA to

$body = [pscustomobject]@{ sla = ( @{ id = $SlaId } ) }

$tdMethodParams = @{
Uri = "$((Get-TdUrl)/tas/api/incidents/number/$($Number.ToLower())"
Body = $body
Method = 'Put'
}

Invoke-TdMethod @tdMethodparams
```

Let me know if this works for you. If it does I can add the functionality to the module. Thanks for raising this issue and providing feedback!

**Comment by BND-ErwinVos** [comment]
When I request the slaid with 
`Get-TdIncident | Select -ExpandPropert sla`
The returned value is a DateTime value

The Incident object returns sla as Hashtable with the property targetDate.

**Comment by AndrewPla** [comment]
Darn, doesn't look like we got anything here. You can suggest that TOPdesk implement this feature. If they implement it we can definitely update the module to include support for it. I'm going to close this issue for now, but reopen it if things change. 

Thanks for giving the module a shot!
