### ISSUE TITLE
Possibility to interact with Active Directory?

### ISSUE THREAD

**Issue by whatthehomepod** [AndrewPla/TOPdeskPS#77]
A showcase:

A new employee needs to have an user account, the servicedesk is preparing and awaiting confirmation through a ticket (comes through a RFC, into a form) from HR. This deparment will set the status that their activity is done and request the servicedesk to start their activity. 

It would be awesome, if TOPdeskAPI would read the change and creates based on that the user account. 

Edit: I’m on a mobile device. Sorry for any incorrect layout or something, will update issue later.

**Comment by AndrewPla** [comment]
The ability to interact with changes in a way similar to what you describe is currently possible. Writing specific commands for that type of stuff may be out of the scope of this project.

I could cover something like you describe in a blog post and you could then apply it to your environment. 

If you can further specify what you are trying to do I can point you in the direction of some commands that accomplish what you are going for.

**Comment by whatthehomepod** [comment]
Thank you for replying!
I would love to see a blog post sometime. 

Verstuurd vanaf mijn iPhone
